#!/usr/bin/env bash

DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck disable=SC1091
source "$DIR"/common.sh

git --version &>/dev/null || install_package git

safe_symlink "$DIR"/.gitconfig ~/.gitconfig
safe_symlink "$DIR"/.gitattributes ~/.gitattributes

hg --version &>/dev/null || install_package mercurial
safe_symlink "$DIR"/.hgrc ~/.hgrc
