#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

git --version >/dev/null || sudo apt-get install -y git
ln -s $DIR/.gitconfig ~/.gitconfig

hg --version >/dev/null || sudo apt-get install -y mercurial
ln -s $DIR/.hgrc ~/.hgrc
