#!/usr/bin/env bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

git --version &>/dev/null || sudo dnf install -y git
ln -s $DIR/.gitconfig ~/.gitconfig
ln -s $DIR/.gitattributes ~/.gitattributes

hg --version &>/dev/null || sudo dnf install -y mercurial
ln -s $DIR/.hgrc ~/.hgrc
