#!/bin/bash

# favourite apps
dconf load /org/gnome/shell/ <<EOF
[/]
favorite-apps=['mozilla-firefox.desktop','gnome-terminal.desktop']
EOF

# icon theme
if [ ! -f /tmp/faenza-icon-theme_1.3.zip ]; then
    wget -P /tmp http://faenza-icon-theme.googlecode.com/files/faenza-icon-theme_1.3.zip
fi
mkdir /tmp/faenza
pushd .
cd /tmp/faenza
unzip /tmp/faenza-icon-theme_1.3.zip
popd

/tmp/faenza/INSTALL

# show date in clock, scale, icons, theme
dconf load /org/gnome/desktop/interface/ <<EOF
[/]
clock-show-date=true
text-scaling-factor=0.8
icon-theme='Faenza-Dark'
gtk-theme='Adwaita'
EOF

# wm theme
dconf load /org/gnome/desktop/wm/preferences/ <<EOF
[/]
theme='Adwaita'
EOF
