#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

# zshell
zsh --version &>/dev/null || sudo dnf install -y zsh

git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
ln -s $DIR/.zshrc ~/.zshrc
sudo chsh -s /bin/zsh $USER

git clone git://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone git://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

# patched fonts with extra symbols
mkdir -p ~/.fonts
git clone git@github.com:powerline/fonts.git ~/.fonts/powerline-fonts
ln -s $DIR/.fonts.conf ~/.fonts.conf
fc-cache -vf ~/.fonts

# Gnome Terminal configuration
dconf load /org/gnome/terminal/legacy/ <<EOF
[profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
visible-name='squeaky'
use-system-font=false
background-color='rgb(0,0,0)'
use-theme-colors=false
foreground-color='rgb(255,255,255)'
background-transparency-percent=5
background-type='transparent'
font='Terminess Powerline Regular 12'
scrollback-unlimited=true
scrollbar-policy='never'

[/]
schema-version=uint32 3
default-show-menubar=false
EOF
