#!/usr/bin/env bash

vim --version  >/dev/null || sudo dnf install -y vim-X11

DIR="$( cd "$( dirname "$0" )" && pwd )"

ln -s $DIR/.vimrc ~/.vimrc
ln -s $DIR/.vim ~/.vim

mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

vim +BundleInstall +qall
