#!/bin/bash

# favourite apps
dconf load /org/gnome/shell/ <<EOF
[/]
favorite-apps=['google-chrome.desktop','gnome-terminal.desktop']
EOF

# window theme
sudo add-apt-repository -y ppa:webupd8team/themes
sudo apt-get update
sudo apt-get install -y mediterraneannight-gtk-theme

# icon theme
if [ ! -f /tmp/faenza-icon-theme_1.3.1_all.deb ]; then
    wget -P /tmp https://launchpad.net/~tiheum/+archive/equinox/+files/faenza-icon-theme_1.3.1_all.deb
fi
sudo dpkg -i /tmp/faenza-icon-theme_1.3.1_all.deb

# show date in clock, scale, icons, theme
dconf load /org/gnome/desktop/interface/ <<EOF
[/]
clock-show-date=true
text-scaling-factor=0.8
icon-theme='Faenza-Ambiance'
gtk-theme='MediterraneanNight'
EOF

# wm theme
dconf load /org/gnome/desktop/wm/preferences/ <<EOF
[/]
theme='MediterraneanNight'
EOF
