#!/bin/bash

set -e

FEDORA_VERSION=`lsb_release -rs`

sudo tee -a /etc/yum.repos.d/docker-main.repo <<-EOF
[docker-main-repo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/fedora/$FEDORA_VERSION
enabled=1
gpgcheck=1
gpg_key=https://yum.dockerproject.org/gpg
EOF

sudo cp docker/overlayfs.conf /etc/modules-load.d
sudo modprobe overlay

sudo mkdir -p /etc/systemd/system/docker.service.d
sudo cp docker/storage-driver.conf /etc/systemd/system/docker.service.d

sudo dnf install -y docker-engine
sudo systemctl daemon-reload
sudo systemctl start docker
sudo systemctl enable docker

sudo gpasswd -a $USER docker

sudo su - $USER -c "docker info && docker run --rm busybox echo Success"
