#!/bin/bash

# Configure quick access commands
xdotool -v >/dev/null || sudo apt-get install -y xdotool

RAISE="$( cd "$( dirname "$0" )" && pwd )"/raise.py


dconf load /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ <<EOF
[custom1]
binding='<Alt>1'
command='$RAISE google-chrome'
name='google-chrome'

[custom0]
binding='<Alt>2'
command='$RAISE gnome-terminal'
name='gnome-terminal'
EOF

# Layout, swap esc with capslock and enable compose key
dconf load /org/gnome/desktop/input-sources/ <<EOF
[/]
sources=[('xkb', 'us+altgr-intl'), ('xkb', 'pl')]
xkb-options=['caps:swapescape', 'compose:rwin']
EOF
