#!/bin/bash

# Configure quick access commands
xdotool -v >/dev/null || sudo apt-get install -y xdotool

RAISE="$( cd "$( dirname "$0" )" && pwd )"/raise.py


dconf load /org/gnome/settings-daemon/plugins/media-keys/ <<EOF
[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']

[custom-keybindings/custom1]
binding='<Alt>1'
command='$RAISE google-chrome'
name='google-chrome'

[custom-keybindings/custom0]
binding='<Alt>2'
command='$RAISE gnome-terminal'
name='gnome-terminal'
EOF

# Touchpad
dconf load /org/gnome/settings-daemon/peripherals/touchpad/ <<EOF
[/]
scroll-method='two-finger-scrolling'
horiz-scroll-enabled=true
tap-to-click=false
EOF

# Layout, swap esc with capslock and enable compose key
dconf load /org/gnome/desktop/input-sources/ <<EOF
[/]
sources=[('xkb', 'us+altgr-intl'), ('xkb', 'pl')]
xkb-options=['caps:swapescape', 'compose:rwin']
EOF
