#!/bin/bash

DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck disable=SC1091
source "$DIR"/common.sh

zsh --version &>/dev/null || install_package zsh

safe_clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
safe_symlink "$DIR"/.zshrc ~/.zshrc
if [ "$(detect_os)" != "Darwin" ]; then
    sudo usermod -s /bin/zsh "$USER"
fi

safe_clone git://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
safe_clone git://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

mkdir -p ~/.local/bin
tmpfile=$(mktemp /tmp/install-starship.XXXXXX)
curl -fsSL --output "$tmpfile" https://starship.rs/install.sh
chmod a+x "$tmpfile"
"$tmpfile" -b ~/.local/bin -y
mkdir -p ~/.config
safe_symlink "$DIR"/starship.toml ~/.config/starship.toml

if [ "$(detect_os)" != "Darwin" ]; then
	# patched fonts with extra symbols
	mkdir -p ~/.fonts
	safe_clone git@github.com:powerline/fonts.git ~/powerline-fonts
	~/powerline-fonts/install.sh
fi

if dconf help &>/dev/null; then
	# Gnome Terminal configuration
	dconf load /org/gnome/terminal/legacy/ <<EOF
[profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
visible-name='squeaky'
use-system-font=false
background-color='rgb(0,0,0)'
use-theme-colors=false
foreground-color='rgb(255,255,255)'
background-transparency-percent=5
background-type='transparent'
font='Terminess Powerline Regular 12'
scrollback-unlimited=true
scrollbar-policy='never'

[/]
schema-version=uint32 3
default-show-menubar=false
EOF
fi
