#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

# tmux
tmux -V &>/dev/null || sudo `./get-install-cmd` tmux
ln -s $DIR/.tmux.conf ~/.tmux.conf

# tmux powerline
git clone git@github.com:squeaky-pl/tmux-powerline.git ~/.tmux-powerline

# zshell
zsh --version &>/dev/null || sudo `./get-install-cmd` zsh

git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
ln -s $DIR/.zshrc ~/.zshrc
sudo chsh -s /bin/zsh $USER

git clone git://github.com/tarruda/zsh-autosuggestions ~/.zsh-autosuggestions

# patched fonts with extra symbols
mkdir -p ~/.fonts
git clone git@github.com:Lokaltog/powerline-fonts.git ~/.fonts/powerline-fonts
ln -s $DIR/.fonts.conf ~/.fonts.conf
fc-cache -vf ~/.fonts

# Gnome Terminal configuration
dconf load /org/gnome/terminal/legacy/ <<EOF
[profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
visible-name='squeaky'
use-system-font=false
background-color='rgb(0,0,0)'
use-theme-colors=false
foreground-color='rgb(255,255,255)'
background-darkness=0.9
background-type='transparent'
font='Terminess Powerline 12'
scrollback-unlimited=true
scrollbar-policy='never'

[/]
schema-version=uint32 3
EOF
