#!/bin/bash

sudo `./get-install-cmd` python-dev python-devel python-pip
sudo pip install --upgrade pip
sudo pip install virtualenv pylama py3kwarn virtualenvwrapper

mkdir -p ~/workspace
mkdir -p ~/.virtualenvs
