#!/bin/bash

# favourite apps
dconf load /org/gnome/shell/ <<EOF
[/]
favorite-apps=['mozilla-firefox.desktop','gnome-terminal.desktop']
EOF

# window theme
if [ ! -f /tmp/MediterraneanNight-2.03.tar.gz ]; then
    wget -P /tmp https://dl.dropboxusercontent.com/u/80497678/MediterraneanNight-2.03.tar.gz
fi
mkdir -p ~/.themes
tar -C ~/.themes -xf /tmp/MediterraneanNight-2.03.tar.gz

# icon theme
if [ ! -f /tmp/faenza-icon-theme_1.3.zip ]; then
    wget -P /tmp http://faenza-icon-theme.googlecode.com/files/faenza-icon-theme_1.3.zip
fi
mkdir /tmp/faenza
pushd .
cd /tmp/faenza
unzip /tmp/faenza-icon-theme_1.3.zip
popd

/tmp/faenza/INSTALL

# show date in clock, scale, icons, theme
dconf load /org/gnome/desktop/interface/ <<EOF
[/]
clock-show-date=true
text-scaling-factor=0.8
icon-theme='Faenza-Ambiance'
gtk-theme='MediterraneanNight'
EOF

# wm theme
dconf load /org/gnome/desktop/wm/preferences/ <<EOF
[/]
theme='MediterraneanNight'
EOF
